### ISSUE TITLE
`make` error

### ISSUE THREAD

**Issue by zzz6519003** [msgport/msgport#227]
I pass through `make tools`

but when I run `make`

```

➜  darwinia-msgport git:(315caa7) make
thread 'main' panicked at /Users/mac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/forge-0.1.0/src/config.rs:21:41:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/result.rs:1653:5
   3: forge::config::Config::open
   4: forge::build::build
   5: forge::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
make: *** [all] Error 101

```

```
➜  darwinia-msgport git:(315caa7) export RUST_BACKTRACE=full
➜  darwinia-msgport git:(315caa7) make                      
thread 'main' panicked at /Users/mac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/forge-0.1.0/src/config.rs:21:41:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:        0x102cb7098 - std::backtrace_rs::backtrace::libunwind::trace::h9cd157705f836c88
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102cb7098 - std::backtrace_rs::backtrace::trace_unsynchronized::h030508cad0c96506
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102cb7098 - std::sys_common::backtrace::_print_fmt::h88a1ed39b4ece298
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x102cb7098 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h609d18d0c85d63a9
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x102cd311c - core::fmt::rt::Argument::fmt::hdbd821070d8fdaa4
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/fmt/rt.rs:142:9
   5:        0x102cd311c - core::fmt::write::h5ef2243eaaf6ccd2
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/fmt/mod.rs:1117:17
   6:        0x102cb5230 - std::io::Write::write_fmt::h21d1439131c35d3b
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/io/mod.rs:1762:15
   7:        0x102cb6ed4 - std::sys_common::backtrace::_print::h1ddb762a0bfe53eb
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x102cb6ed4 - std::sys_common::backtrace::print::hd350b5b9c66d7a94
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x102cb8488 - std::panicking::default_hook::{{closure}}::h6947ff5e9fd88169
  10:        0x102cb81d0 - std::panicking::default_hook::hf5149699eaa4a5dd
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:292:9
  11:        0x102cb88b0 - std::panicking::rust_panic_with_hook::h898554c4a28fae4a
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:731:13
  12:        0x102cb87b0 - std::panicking::begin_panic_handler::{{closure}}::hc27d75341282fb81
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:609:13
  13:        0x102cb7500 - std::sys_common::backtrace::__rust_end_short_backtrace::h0d9b8a62ead1f87f
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/sys_common/backtrace.rs:170:18
  14:        0x102cb854c - rust_begin_unwind
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:597:5
  15:        0x102cdcf70 - core::panicking::panic_fmt::h3fc5ad127547e2b3
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/panicking.rs:72:14
  16:        0x102cdd290 - core::result::unwrap_failed::h73a12b1cf04211f7
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/result.rs:1653:5
  17:        0x102c8a944 - forge::config::Config::open::h7d27323aee7e84f9
  18:        0x102c857d8 - forge::build::build::h4adf626d223edc83
  19:        0x102c88d80 - forge::main::hd83130f968f6a40b
  20:        0x102c88714 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdd21f51553ae953f
  21:        0x102c8aedc - std::rt::lang_start::{{closure}}::h68a7269ea052d7f5
  22:        0x102cb1724 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2b21e4ad5b80e233
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/core/src/ops/function.rs:284:13
  23:        0x102cb1724 - std::panicking::try::do_call::h43c52f100584c9f5
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:504:40
  24:        0x102cb1724 - std::panicking::try::h08bc359590a147d0
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:468:19
  25:        0x102cb1724 - std::panic::catch_unwind::h2b7ad31d5a0c0238
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panic.rs:142:14
  26:        0x102cb1724 - std::rt::lang_start_internal::{{closure}}::ha8d16fe1a13ef7e3
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/rt.rs:148:48
  27:        0x102cb1724 - std::panicking::try::do_call::hbfb54b3031b93094
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:504:40
  28:        0x102cb1724 - std::panicking::try::hc38f1412765843cf
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panicking.rs:468:19
  29:        0x102cb1724 - std::panic::catch_unwind::h646170fbb6087523
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/panic.rs:142:14
  30:        0x102cb1724 - std::rt::lang_start_internal::h19ea4013fb2b42c5
                               at /rustc/df871fbf053de3a855398964cd05fadbe91cf4fd/library/std/src/rt.rs:148:20
  31:        0x102c8aec0 - std::rt::lang_start::hec69dc0b74e626e2
  32:        0x102c88eb4 - _main
make: *** [all] Error 101

```

**Comment by hujw77** [comment]
Could you show me your project files by `tree -L 2`?

**Comment by zzz6519003** [comment]
At your command XD
```bash
➜  darwinia-msgport git:(315caa7) tree -L 2
.
├── Makefile
├── README.md
├── SUPPORTED.md
├── SUPPORTED_XACCOUNT.md
├── bin
│   ├── add.sh
│   ├── config.sh
│   ├── dao.sh
│   ├── deploy.sh
│   └── verify.sh
├── foundry.toml
├── ipfs
│   ├── multi.json
│   ├── ormp.json
│   └── x_account_factory.json
├── lib
│   ├── ORMP
│   ├── axelar-gmp-sdk-solidity
│   ├── create3-deploy
│   ├── darwinia-messages-sol
│   ├── forge-std
│   ├── openzeppelin-contracts
│   ├── safe-deployments
│   ├── sgn-v2-contracts
│   ├── solidity-examples
│   └── solmate
├── package.json
├── remappings.txt
├── script
│   ├── config
│   ├── deploy
│   ├── input
│   ├── output
│   └── test
└── src
    ├── PortRegistry.sol
    ├── PortRegistryProxy.sol
    ├── chain-id-mappings
    ├── examples
    ├── interfaces
    ├── ports
    ├── user
    ├── utils
    └── xAccount

28 directories, 17 files

```

**Comment by hujw77** [comment]
You could use `foundryup` command to update tools.

**Comment by zzz6519003** [comment]
updated, but still same error 😹
